### ISSUE TITLE
Deleting pages does not remove them from the output file

### ISSUE THREAD

**Issue by m-holger** [pikepdf/pikepdf#196]
Deleting pages using, for example,
``` python
pdf = Pdf.open('./pikepdf-readthedocs-io-en-latest.pdf')
del(pdf.pages[1:])
pdf.save('./out.pdf')
```
does not remove them (or their contents) from the output file.

The problem appears to be that `del()` simply removes the pages from the page tree without replacing them with a `null` object. If the pages are referred to by other objects, eg as destinations, they will be included in the output file even though they are inaccessible.

Related issues are reported at https://github.com/qpdf/qpdf/issues/520

**Comment by jbarlow83** [comment]
Thanks. I think this will be left alone until qpdf addresses the issue.

**Comment by m-holger** [comment]
>  I think it will be best to leave this alone until qpdf addresses the issue

That sounds like a reasonable approach to me. However, given the potential for confusion and frustration I think it would be highly desirable to expand the documentation (perhaps the tutorial?) to discuss the pitfalls and possible workarounds in the meantime. This feels particularly important given that some users of pikepdf will continue supporting older versions of pikepdf and therefore any improvements in qpdf will take some time to filter down to applications such PDF Arranger. 

To illustrate how to deal with the page deletion problem (as well as the page moving problem raised in #192) I have written a short script to extract the index page and the pages for the  `add_resource()` and `encode()` methods  from the pikepdf documentation. In the output file the "Index" entry in the outline as well as the links to   `add_resource()` and `encode()` in the index are working. The size of the output file is 172kB compared to 1.6MB for the very similar file in https://github.com/pikepdf/pikepdf/issues/192#issuecomment-817643633.

``` python
from copy import copy
from pikepdf import *

def extract(pages, page):
    '''extract a page for later reinsertion'''
    index = pages.index(page)
    pages[index] = copy(page)
    return page

def delete_page(pages, page):
    '''remove page from the page tree and delete page content so that it can be removed from the output file'''
    index = pages.index(page)
    for key in page.keys():
        del(page[key])
    del(pages[index])

def true_append(pages, page):
    '''append the actual page, not a copy (so that bookmarks do not get broken)'''
    pdf._add_page(page)

pdf = Pdf.open('./pikepdf-readthedocs-io-en-latest.pdf')

index_page = extract(pdf.pages, pdf.pages.p(89))
add_resource_page = extract(pdf.pages, pdf.pages.p(72))
encode_page = extract(pdf.pages, pdf.pages.p(74))

for page in [page for page in pdf.pages]:
    delete_page(pdf.pages, page)

true_append(pdf.pages, index_page)
true_append(pdf.pages, add_resource_page)
true_append(pdf.pages, encode_page)

pdf.save('./out.pdf', object_stream_mode=ObjectStreamMode.generate) 
#object_stream_mode=ObjectStreamMode.generate is critical to ensure unreferenced objects are removed
```
Many thanks to @jberkenbilt for his kind help.

**Comment by jberkenbilt** [comment]
Let me just add a little clarity. There are three object stream modes in qpdf: `disable`, `preserve`, and `generate`. The default is `preserve`. In `preserve` mode, if the input file uses object streams, the output file will use the same object streams with the same objects in them, and if the input file does not have object streams, the output file will not have them either. In `disable` mode, the output file will not have object streams. In `generate` mode, qpdf will create its own object streams and distribute objects in its own way. Unless otherwise directed, QPDFWriter will not write out any objects that are unreferenced, but there is a long-standing, known bug which is that in the one case of `preserve` mode, unreferenced objects inside object streams are retained. When I implemented object streams, page splitting and so forth was not in the library, so this bug only caused unreferenced objects that were present and unreferenced in the original file and was therefore not that important. When I added page splitting functionality, this became more important, and I should have fixed it at that time, but I guess it faded from my consciousness in spite of the fact that there is a note about it in TODO.

If you explicitly use `generate` mode, you are causing object streams to be created in files that don't otherwise have them. This is not necessarily a bad thing, but there may be cases in which this is not desirable. When I added object stream support to qpdf, it was still relatively rare to find it in open source tools (and some commercial ones), so `qpdf --object-streams=disable` was a useful way to make these files usable with older readers. However object streams have been around for so long now that I doubt that's much of an issue anymore. Using `generate` forces the version in the PDF header to be >= 1.5.

That's probably all you really need to know about this.

@m-holger I am probably going to send something out to the qpdf-announce list at some point to discuss a future API for doing page-level operations. Are you subscribed? My plan is to create a discussion issue on github and announce the issue on the announce list, not to have any discussion on the list. I would welcome your input if you are inclined. I don't know when this will happen. Hopefully this summer sometime.

**Comment by mara004** [comment]
As far as I can see, this issue is fixed as of pikepdf 2.16.1 / libqpdf 10.3.2.

**Comment by m-holger** [comment]
The issue is still present in pikepdf 4.2.0 / libqpdf 10.4.0

Tested with:
```python
pdf = Pdf.open('./pikepdf-readthedocs-io-en-latest.pdf')
while len(pdf.pages) > 1:
    page = pdf.pages[-1]
    del(pdf.pages[-1])
    #for key in page.keys():
        #del(page[key])

pdf.save('./out.qdf', qdf=True)
```
Uncommenting the lines in the script ensures the deleted pages are not included in the output file.

The related qpdf issue was fixed in libqpdf 10.3.2

**Comment by mara004** [comment]
It works in the sense that the deleted pages are not shown in the PDF viewer anymore. However, you're right that the data of deleted pages is still present in the output file, causing it to be unnecessarily large.

**Comment by jbarlow83** [comment]
Resolving this as a **documentation** change rather than a behavior change.

The original blocker—qpdf retaining unreferenced objects in *preserved* object streams (qpdf#520)—was fixed in qpdf 10.3.2. Since pikepdf now requires qpdf ≥ 12.2.0, a plain `del pdf.pages[...]` already fully removes pages that nothing else references (the common case), and the `object_stream_mode=generate` workaround is no longer needed for that.

The remaining behavior is by design: a page still referenced by an outline, link annotation, or named destination stays reachable, so qpdf keeps it (and its content) on save. Removing that reference—or the page's own content—is the caller's responsibility, and qpdf exposes no API to chase down and rewrite every destination automatically. (`fix_dangling_references()` does not help here; it materializes references to *missing* objects, the opposite problem.)

So, following @m-holger's suggestion, we've documented the pitfall and two workarounds (remove the referencing object, or strip the page's content before deleting) in a new **Deleting pages** topic, with a cross-reference from the tutorial. Shipping in v10.9.0.

Thanks @m-holger and @jberkenbilt for the analysis.
